apiVersion: v1
kind: Pod
metadata: 
  name: testpod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx
---
timeout: 180
---
apiVersion: v1
kind: Pod
metadata: 
  name: testpod1
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx
